apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: compliment-generator
- path: patch-service.yaml
  target:
    kind: Service
    name: compliment-generator-service
images:
- name: elipavlov/rtproject
  newName: elipavlov/rtproject
  newTag: latest-0d1e5e9
