apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliment-generator
spec:
  selector:
    matchLabels:
      app: compliment-generator
  template:
    metadata:
      labels:
        app: compliment-generator
    spec:
      containers:
        - name: compliment-generator
          image: elipavlov/rtproject  # <- No tag here
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            periodSeconds: 15
            timeoutSeconds: 2
            successThreshold: 2
            failureThreshold: 2
