apiVersion: v1
kind: Service
metadata:
  name: compliment-generator-service
  labels:
    app: compliment-generator
spec:
  selector:
    app: compliment-generator
  ports:
    - port: 80
      targetPort: 5000
  type: NodePort
