frontend:
  app: { name: frontend, type: frontend, syncWave: "2" }

  image:
    repository: elipavlov/newsapp-frontend
    tag: dev-local  # CI updates

  service:
    type: ClusterIP
    port: 8080

  nodeSelector: { role: application }

  # Prefer spreading frontend pods across nodes 1 & 2 (role=application)
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: ["frontend"]
            topologyKey: kubernetes.io/hostname

  # Modest resource envelope
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  env:
    plain:
      VITE_SERVER_URL: "/api"
      VITE_NEWS_INTERVAL_IN_MIN: "5"
      BACKEND_SERVICE_HOST: "backend.development.svc.cluster.local"
      BACKEND_SERVICE_PORT: "8080"

  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      cert-manager.io/cluster-issuer: letsencrypt-staging
    hosts:
      - host: newsapp-dev.weblightenment.com
        paths:
          - path: /(.*)
            pathType: Prefix
    tls:
      - hosts: ["newsapp-dev.weblightenment.com"]
        secretName: newsapp-dev-tls
