app: { name: frontend, type: frontend }

image:
  repository: elipavlov/newsapp-frontend
  tag: dev-local  # CI updates

service:
  type: NodePort
  port: 80
  nodePort: 30080

nodeSelector: { kubernetes.io/hostname: node-1 }
securityContext: { addNetBindService: true }

env:
  plain:
    VITE_SERVER_URL: "/api"
    VITE_NEWS_INTERVAL_IN_MIN: "5"
    BACKEND_SERVICE_HOST: "backend.development.svc.cluster.local"
    BACKEND_SERVICE_PORT: "8080"
