app:
  name: frontend

image:
  repository: your-dockerhub/newsapp-frontend
  tag: dev-local     # CI updates this

service:
  type: ClusterIP
  port: 80

env:
  plain:
    VITE_SERVER_URL: "/api"
    VITE_NEWS_INTERVAL_IN_MIN: "5"
    BACKEND_SERVICE_HOST: "backend.development.svc.cluster.local"
    BACKEND_SERVICE_PORT: "8080"
