app:
  name: frontend

image:
  repository: your-dockerhub/newsapp-frontend
  tag: latest-local  # CI updates this

service:
  type: ClusterIP
  port: 80

env:
  plain:
    VITE_SERVER_URL: "/api"
    VITE_NEWS_INTERVAL_IN_MIN: "5"
    BACKEND_SERVICE_HOST: "backend.default.svc.cluster.local"
    BACKEND_SERVICE_PORT: "8080"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: news.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: newsapp-tls
      hosts:
        - news.example.com
