app:
  name: frontend
image:
  repository: elipavlov/newsapp-frontend
  tag: latest-ec40111 # CI updates this
service:
  type: ClusterIP
  port: 80
env:
  plain:
    VITE_SERVER_URL: "/api"
    VITE_NEWS_INTERVAL_IN_MIN: "5"
    BACKEND_SERVICE_HOST: ""
    BACKEND_SERVICE_PORT: ""
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: news.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: newsapp-tls
      hosts:
        - news.example.com
