app: { name: frontend, type: frontend }

image:
  repository: elipavlov/newsapp-frontend
  tag: latest-local  # CI updates

service:
  type: ClusterIP
  port: 80

nodeSelector: { kubernetes.io/hostname: node-1 }
securityContext: { addNetBindService: true }

env:
  plain:
    VITE_SERVER_URL: "/api"
    VITE_NEWS_INTERVAL_IN_MIN: "5"
    BACKEND_SERVICE_HOST: "backend.default.svc.cluster.local"
    BACKEND_SERVICE_PORT: "8080"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: news.example.com
      paths:
        - path: /(.*)
          pathType: Prefix
  tls:
    - hosts: ["news.example.com"]
      secretName: newsapp-tls
