app: { name: frontend, type: frontend }
image:
  repository: ghcr.io/eli-pavlov/newsapp/frontend
  tag: latest
service:
  type: ClusterIP
  port: 80
  hostPort: 80                    # exposed on node-1:80
nodeSelector: { kubernetes.io/hostname: node-1 }
securityContext:
  addNetBindService: true         # allow bind to port 80 for non-root images
env:
  plain:
    VITE_SERVER_URL: "http://NODE2_IP:30001"    # CI will replace NODE2_IP
    VITE_NEWS_INTERVAL_IN_MIN: "5"
