frontend:
  app: { name: frontend, type: frontend, syncWave: "2" }

  replicaCount: 2

  image:
    repository: elipavlov/newsapp-frontend
    tag: latest-ec40111 # CI updates

  service:
    type: ClusterIP
    port: 8080

  nodeSelector: { role: application }

  # Spread FE pods across node1+2 by component label
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values: ["frontend"]
            topologyKey: kubernetes.io/hostname

  # Modest resources
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  env:
    plain:
      VITE_SERVER_URL: "/api"
      VITE_NEWS_INTERVAL_IN_MIN: "5"
      BACKEND_SERVICE_HOST: "" # CI fills
      BACKEND_SERVICE_PORT: "" # CI fills

  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: newsapp.weblightenment.com
        paths:
          - path: /
            pathType: Prefixx
    tls:
      - hosts: ["newsapp.weblightenment.com"]
        secretName: newsapp-tls
