app: { name: frontend, type: frontend }
image:
  repository: ghcr.io/eli-pavlov/newsapp/frontend
  tag: latest
service:
  type: ClusterIP
  port: 80
  hostPort: 80
nodeSelector: { kubernetes.io/hostname: node-1 }
securityContext:
  addNetBindService: true
env:
  plain:
    VITE_SERVER_URL: "/api"
    VITE_NEWS_INTERVAL_IN_MIN: "5"
