apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newsapp-master-app
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer-foreground
spec:
  project: default
  source:
    repoURL: https://github.com/eli-pavlov/newsapp-manifests.git
    targetRevision: main
    path: clusters
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true