app:
  name: app
  type: backend # or "frontend"

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP  # ClusterIP | NodePort
  port: 80         # containerPort / service port
  nodePort: null   # e.g. 3080 for dev frontend
  hostPort: null   # e.g. 80 for prod frontend (requires capability)

resources: {}

nodeSelector: {}
tolerations: []
affinity: []

imagePullSecrets: []

env:
  # literal envs (e.g. frontend VITE_* and backend DB_ENGINE_TYPE)
  plain: {}     # key: value
  # bring in a secret as env (e.g. backend DB_URI)
  secretRef: "" # e.g. backend-secrets
  # optional configmap
  configRef: ""

securityContext:
  # allow container to bind <1024 like port 80 if image runs non-root
  addNetBindService: false

# Frontend extras
frontend:
  # If you also want a NodePort instead of hostPort, set service.type=NodePort and nodePort
  # For hostPort exposure set service.hostPort=80 and securityContext.addNetBindService=true if non-root

# Backend extras
backend:
  # expose backend via NodePort for the browser
  nodePort: 3001
