app:
  name: website
  syncWave: "2"

replicaCount: 1

image:
  repository: elipavlov/weblightenment-website
  tag: dev-001               # <-- set to the tag you pushed
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80                   # nginx listens on 80 inside the container
  nodePort: null
  hostPort: null

nodeSelector:
  role: application

affinity: {}
tolerations: []

env:
  plain: {}
  secretRefs: []
  configRefs: []

resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: true
  className: nginx
  annotations:
    # Staging issuer for testing
    cert-manager.io/cluster-issuer: letsencrypt-staging-dns01-cloudflare
  hosts:
    - host: website-dev.weblightenment.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - website-dev.weblightenment.com
      secretName: website-dev-tls   # cert-manager will create this

hpa:
  enabled: false

probes:
  readiness:
    enabled: true
    type: http
    path: /
  liveness:
    enabled: true
    type: http
    path: /
  startup:
    enabled: false

networkPolicy:
  enabled: false
