apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: newsapp
  namespace: argocd
spec:
  description: NewsApp project
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/eli-pavlov/newsapp-manifests.git
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
