apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: newsapp-prod
  namespace: argocd
spec:
  description: Production project for newsapp
  sourceRepos:
    - https://github.com/eli-pavlov/newsapp-manifests.git
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
clusterResourceWhitelist:
  - group: 'apps'
    kind: 'Deployment'
  - group: 'apps'
    kind: 'StatefulSet'
  - group: ''
    kind: 'Service'
  - group: 'networking.k8s.io'
    kind: 'Ingress'
  - group: 'autoscaling'
    kind: 'HorizontalPodAutoscaler'