app: { name: backend, type: backend }
fullnameOverride: backend

image:
  repository: ghcr.io/eli-pavlov/newsapp/backend
  tag: latest

service:
  type: ClusterIP
  port: 8080

# keep if you want to pin nodes; otherwise remove this block
# nodeSelector: { kubernetes.io/hostname: node-2 }

env:
  plain:
    DB_ENGINE_TYPE: "MYSQL"
  secretRef: backend-secrets
