app: {name: backend, type: backend}
image:
  repository: elipavlov/newsapp-backend
  tag: latest-6b42e0e
service:
  type: NodePort
  port: 8080
  nodePort: 30001 # valid NodePort range
nodeSelector: {kubernetes.io/hostname: node-2}
env:
  plain:
    DB_ENGINE_TYPE: "MYSQL"
  secretRef: backend-secrets # CI creates this with DB_URI
