backend:
  app: { name: backend, type: backend }
  fullnameOverride: backend

  image:
    repository: elipavlov/newsapp-backend
    tag: dev-local

  service:
    type: ClusterIP
    port: 8080

  # Run BE only on application workers
  nodeSelector: { role: application }

  # Prefer spreading backend pods across nodes 1 & 2 (role=application)
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: ["backend"]
            topologyKey: kubernetes.io/hostname

  # Modest resource envelope
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  env:
    plain:
      DB_ENGINE_TYPE: "POSTGRES"
    # Use the connection string secret created by bootstrap:
    secretRef: backend-db-connection

# In-cluster DB for dev (pinned to DB node, using Local PV backed by OCI block volume)
db:
  enabled: true
  service:
    name: postgresql-dev
    port: 5432
    type: ClusterIP
  dbName: newsdb_dev

  # Pin to DB worker and tolerate its taint
  nodeSelector: { role: database }
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"

  existingSecret:
    name: postgres-credentials
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD

  storage:
    size: 10Gi
    storageClassName: "local-db-dev"
