app:
  name: backend
  syncWave: "1"
fullnameOverride: backend
replicaCount: 2
image:
  repository: elipavlov/newsapp-backend
  tag: latest-66766bc
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
nodeSelector:
  role: application
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values: ["backend"]
          topologyKey: kubernetes.io/hostname
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  plain:
    DB_ENGINE_TYPE: "POSTGRES"
  secretRef: backend-db-connection
hpa:
  enabled: false
networkPolicy:
  backendEgressWeb:
    enabled: true
  backendEgressDb:
    enabled: true
    dbNamespace: development
    dbSelector:
      matchLabels:
        app.kubernetes.io/name: postgresql-dev
    dbPort: 5432