app:
  name: backend
  syncWave: "1"
fullnameOverride: backend
replicaCount: 1
image:
  repository: elipavlov/newsapp-backend
  tag: dev-e8d4f91
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values: ["backend"]
          topologyKey: kubernetes.io/hostname
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - application
                - database
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  plain:
    DB_ENGINE_TYPE: "POSTGRES"
    MOVIES_FOLDER: "movies"
  secretRefs:
    - storage-type
    - aws-secret-access-key
    - aws-access-key-id
    - aws-region
    - aws-bucket
    - db-name
    - db-user
    - db-password
    - db-host
    - db-port
    - db-protocol
hpa:
  enabled: false
networkPolicy:
  backendEgressWeb:
    enabled: true
  backendEgressDb:
    enabled: true
    dbNamespace: development
    dbSelector:
      matchLabels:
        app.kubernetes.io/name: postgresql-dev
    dbPort: 5432
persistence:
  enabled: false
