nameOverride: backend
replicaCount: 1
image:
  repository: your-registry.example.com/newsapp/backend
  tag: dev
containerPort: 3000
service:
  port: 3000
ingress:
  enabled: false
env:
  - name: NODE_ENV
    value: development
resources: {}
