app:
  name: backend
  syncWave: "1"
fullnameOverride: backend
replicaCount: 2

image:
  repository: elipavlov/newsapp-backend
  tag: latest-66766bc     # <- updated to an image that exists on Docker Hub
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

nodeSelector:
  role: application

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values: ["backend"]
          topologyKey: kubernetes.io/hostname

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  plain:
    DB_ENGINE_TYPE: "POSTGRES"
  secretRef: backend-db-connection

hpa:
  enabled: false

db:
  enabled: true
  service:
    name: postgresql-dev
    port: 5432
    type: ClusterIP
  dbName: newsdb_dev
  nodeSelector: { role: database }
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"
  existingSecret:
    name: postgres-credentials
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
  storage:
    size: 10Gi
    storageClassName: "local-db-dev"

networkPolicy:
  backendEgressWeb:
    enabled: true
