backend:
  app: { name: backend, type: backend }
  fullnameOverride: backend
  nodeSelector: { role: application }

  image:
    repository: elipavlov/newsapp-backend
    tag: dev-local

  service:
    type: ClusterIP
    port: 8080

  env:
    plain:
      DB_ENGINE_TYPE: "POSTGRES"
    # Use the connection string secret created by bootstrap:
    secretRef: backend-db-connection

# In-cluster DB for dev
db:
  enabled: true
  service:
    name: postgresql-dev
    port: 5432
    type: ClusterIP
  dbName: newsdb_dev
  existingSecret:
    name: postgres-credentials
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
  storage:
    size: 10Gi
    # storageClassName: "local-path"
