app:
  name: backend

image:
  repository: your-dockerhub/newsapp-backend
  tag: dev-local    # CI updates this

service:
  type: ClusterIP
  port: 8080

env:
  # Pull both DB_ENGINE_TYPE and DB_URI from your Secret
  secretRef:
    name: backend-db-env

# If the umbrella chart previously bundled a DB:
postgresql:
  enabled: false
