app:
  name: backend
  syncWave: "1"
fullnameOverride: backend
replicaCount: 2
image:
  repository: elipavlov/newsapp-backend
  tag: dev-b81f516
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
nodeSelector:
  role: application
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values: ["backend"]
          topologyKey: kubernetes.io/hostname
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  plain:
    DB_ENGINE_TYPE: "POSTGRES"
  secretRefs:
    - storage-type
    - aws-secret-access-key
    - aws-access-key-id
    - aws-region
    - aws-bucket
    - db-name
    - db-user
    - db-password
    - db-host
    - db-port
    - db-protocol
hpa:
  enabled: false
networkPolicy:
  backendEgressWeb:
    enabled: true
  backendEgressDb:
    enabled: true
    dbNamespace: development
    dbSelector:
      matchLabels:
        app.kubernetes.io/name: postgresql-dev
    dbPort: 5432
# persistence for ephemeral (emptyDir) mounts
persistence:
  enabled: true             # set to true to enable the emptyDir mount
  type: emptyDir            # only "emptyDir" for this flow
  mountPath: /data/uploads  # path inside container your app will write to
  # If your container runs as non-root, enable chown to set ownership inside the pod.
  chown:
    enabled: true
    uid: 1000
    gid: 1000