app:
  name: backend
  syncWave: "1"
fullnameOverride: backend
replicaCount: 2
image:
  repository: elipavlov/newsapp-backend
  tag: dev-b81f516
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
nodeSelector:
  role: application
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values: ["backend"]
          topologyKey: kubernetes.io/hostname
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  plain:
    DB_ENGINE_TYPE: "POSTGRES"
    DISK_ROOT_PATH: "/app/uploads"   # app expects /app/uploads
  secretRefs:
    - storage-type
    - aws-secret-access-key
    - aws-access-key-id
    - aws-region
    - aws-bucket
    - db-name
    - db-user
    - db-password
    - db-host
    - db-port
    - db-protocol
hpa:
  enabled: false
networkPolicy:
  backendEgressWeb:
    enabled: true
  backendEgressDb:
    enabled: true
    dbNamespace: development
    dbSelector:
      matchLabels:
        app.kubernetes.io/name: postgresql-dev
    dbPort: 5432

# Enable ephemeral emptyDir mount for transient data
persistence:
  enabled: true
  type: emptyDir
  mountPath: /app/uploads
  chown:
    enabled: false   # using chmod 0777 initContainer, chown not required
    uid: 1000
    gid: 1000
    runAsUser: 0

# Ensure the container/pod security context matches (recommended)
podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

containerSecurityContext:
  runAsUser: 1000
  allowPrivilegeEscalation: false
