nameOverride: backend
replicaCount: 2
image:
  repository: your-registry.example.com/newsapp/backend
  tag: prod
containerPort: 3000
service:
  port: 3000
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: backend.example.com
      paths:
        - path: /
          pathType: Prefix
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
