backend:
  app: {name: backend, type: backend}
  fullnameOverride: backend
  replicaCount: 2
  image:
    repository: elipavlov/newsapp-backend
    tag: latest-66766bc
  service:
    type: ClusterIP
    port: 8080
  nodeSelector: {role: application}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values: ["backend"]
            topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    plain:
      DB_ENGINE_TYPE: "POSTGRES"
    secretRef: backend-db-connection

db:
  enabled: true
  service:
    name: postgresql-prod
    port: 5432
    type: ClusterIP
  dbName: newsdb_prod
  nodeSelector: {role: database}
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"
  existingSecret:
    name: postgres-credentials
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
  storage:
    size: 20Gi
    storageClassName: "local-db-prod"
