app: { name: backend, type: backend }
image:
  repository: ghcr.io/eli-pavlov/newsapp/backend
  tag: latest
service:
  type: NodePort
  port: 8080
  nodePort: 3001
nodeSelector: { kubernetes.io/hostname: node-2 }
env:
  plain:
    DB_ENGINE_TYPE: "MYSQL"
  secretRef: backend-secrets
