app:
  name: backend

image:
  repository: your-dockerhub/newsapp-backend
  tag: latest-local   # CI updates this

service:
  type: ClusterIP
  port: 8080

env:
  secretRef:
    name: backend-db-env

postgresql:
  enabled: false
