# values/backend/prod.yaml
app:
  name: backend
  syncWave: "1"
fullnameOverride: backend
replicaCount: 2

image:
  repository: elipavlov/newsapp-backend
  tag: latest-d446f3b
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

nodeSelector:
  role: application

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values: ["backend"]
          topologyKey: kubernetes.io/hostname

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Plain env vars (production)
env:
  plain:
    DB_ENGINE_TYPE: "POSTGRES"
    NODE_ENV: production
  secretRef: backend-db-connection
  ignoreEnvFrom: false
  includeAdminKey: false
  configRef: ""

hpa:
  enabled: false

db:
  enabled: true
  service:
    name: postgresql-prod
    port: 5432
    type: ClusterIP
  dbName: newsdb_prod
  nodeSelector: { role: database }
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"
  existingSecret:
    name: postgres-credentials
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
  storage:
    size: 20Gi
    storageClassName: "local-db-prod"
  waitForDB:
    enabled: true

networkPolicy:
  backendEgressWeb:
    enabled: true
    exceptCidrs: []
    ports: [80, 443]
  backendEgressDb:
    enabled: true
    # explicit selector to match postgres pods in default namespace
    dbSelector:
      matchLabels:
        app.kubernetes.io/name: postgresql-prod
    dbPort: 5432
