# values/backend/prod.yaml
app:
  name: backend
  syncWave: "1"
fullnameOverride: backend
replicaCount: 2
image:
  repository: elipavlov/newsapp-backend
  tag: latest-ccff0d8
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
nodeSelector:
  role: application
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values: ["backend"]
          topologyKey: kubernetes.io/hostname
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  plain:
    DB_ENGINE_TYPE: "POSTGRES"
  # list every SealedSecret name (these are created in the default namespace under clusters/prod/sealed)
  secretRefs:
    - storage-type
    - aws-secret-access-key
    - aws-access-key-id
    - aws-region
    - aws-bucket
    - db-name
    - db-user
    - db-password
    - db-host
    - db-port
    - db-protocol
hpa:
  enabled: false
networkPolicy:
  backendEgressWeb:
    enabled: true
  backendEgressDb:
    enabled: true
    dbNamespace: default
    dbSelector:
      matchLabels:
        app.kubernetes.io/name: postgresql-prod
    dbPort: 5432

# Enable ephemeral emptyDir mount for transient data
persistence:
  enabled: true
  type: emptyDir
  mountPath: /data/uploads
  chown:
    enabled: true
    uid: 1000
    gid: 1000

# Ensure the container/pod security context matches chown (optional but recommended)
podSecurityContext:
  fsGroup: 1000

containerSecurityContext:
  runAsUser: 1000
