# values/backend/prod.yaml
app:
  name: backend
  syncWave: "1"
fullnameOverride: backend
replicaCount: 2
image:
  repository: elipavlov/newsapp-backend
  tag: latest-d446f3b
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
nodeSelector:
  role: application
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values: ["backend"]
          topologyKey: kubernetes.io/hostname
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  plain:
    DB_ENGINE_TYPE: "POSTGRES"
  secretRefs:
    - backend-db-connection
    - storage-type
    - aws-secret-access-key
    - aws-access-key-id
    - aws-region
    - aws-bucket
hpa:
  enabled: false
networkPolicy:
  backendEgressWeb:
    enabled: true
  backendEgressDb:
    enabled: true
    dbNamespace: default
    dbSelector:
      matchLabels:
        app.kubernetes.io/name: postgresql-prod
    dbPort: 5432
