backend:
  app: { name: backend, type: backend }
  fullnameOverride: backend

  replicaCount: 2

  image:
    repository: elipavlov/newsapp-backend
    tag: latest-66766bc

  service:
    type: ClusterIP
    port: 8080

  # Run BE only on application workers
  nodeSelector: { role: application }

  # Spread BE pods across node1+2 by component label
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values: ["backend"]
            topologyKey: kubernetes.io/hostname

  # Modest resources
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  env:
    plain:
      DB_ENGINE_TYPE: "POSTGRES"
    secretRef: backend-db-connection

# In-cluster DB for prod (pinned to DB node, using Local PV backed by OCI block volume)
db:
  enabled: true
  service:
    name: postgresql-prod
    port: 5432
    type: ClusterIP
  dbName: newsdb_prod

  # Pin to DB worker and tolerate its taint
  nodeSelector: { role: database }
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"

  existingSecret:
    name: postgres-credentials
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD

  storage:
    size: 20Gi
    storageClassName: "local-db-prod"
