# manifests/argocd/application-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compliment-generator-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eli-pavlov/github-actions-cicd-manifests
    targetRevision: development
    path: manifests/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
