# values/postgres/dev.yaml
service:
  name: postgresql-dev
  port: 5432
  type: ClusterIP

storage:
  size: 10Gi
  storageClassName: "local-db-dev"

dbName: newsdb_dev

credentials:
  userSecret:
    name: "db-user"
    key: "DB_USER"
  passwordSecret:
    name: "db-password"
    key: "DB_PASSWORD"

nodeSelector:
  role: database

tolerations:
  - key: "role"
    operator: "Equal"
    value: "database"
    effect: "NoSchedule"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi
