# values/postgres/prod.yaml
service:
  name: postgresql-prod
  port: 5432
  type: ClusterIP

storage:
  size: 20Gi
  storageClassName: "local-db-prod"

dbName: newsdb_prod

credentials:
  userSecret:
    name: "db-user"
    key: "DB_USER"
  passwordSecret:
    name: "db-password"
    key: "DB_PASSWORD"

nodeSelector:
  role: database

tolerations:
  - key: "role"
    operator: "Equal"
    value: "database"
    effect: "NoSchedule"

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    memory: 1Gi
