apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # Restrict by admin CIDRs only:
    # REPLACE with your actual admin CIDRs CSV (e.g., "203.0.113.4/32,198.51.100.0/24")
    nginx.ingress.kubernetes.io/whitelist-source-range: "REPLACE_WITH_ADMIN_CIDRS_CSV"
    # Use prod issuer; switch to staging while testing if needed
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: argocd.weblightenment.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
    - host: argocd-dev.weblightenment.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
  tls:
    - hosts: ["argocd.weblightenment.com"]
      secretName: argocd-prod-tls
    - hosts: ["argocd-dev.weblightenment.com"]
      secretName: argocd-dev-tls
