apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    # Install Argo CD after the CRDs are ready but before other addons
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.3.11 # Use a pinned chart version for stability
    helm:
      values: |
        # Use 'server' block to configure the argocd-server component
        server:
          ingress:
            enabled: true
            ingressClassName: "nginx"
            hostname: "argocd.weblightenment.com"
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            tls:
              - secretName: argocd-tls
                hosts:
                  - argocd.weblightenment.com
          # This adds the --insecure flag to the argocd-server deployment
          extraArgs:
            - --insecure
          # This adds the required tolerations so the server can run on the control-plane
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"     
        controller:
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
        repoServer:
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
        dex:
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
        redis:
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true