apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-helm
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-manager
  annotations:
    argocd.argoproj.io/depends-on: '["sealed-secrets-controller"]'
    argocd.argoproj.io/sync-wave: "-90"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
          cainjector:
            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
          webhook:
            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true