apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliment-generator
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: compliment-generator
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
