---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: backend
spec:
  encryptedData:
    DB_URI: AgABjlG1q2VcwXrU8AZvBFCgy+qg5T36ZO3itnY1UpVLfUP8MccCrh+gh7+JXjkWh+Lb+kKrUQs9+cgyJqUPBL1aqaRGo6/UWbWq5Sl6LXHwlyk5g2W0Qy2ywhUswLLBEmRTp3O3FTm42/Six6Y+EvzMeDnjTWyDPNOpJ+KGz2YuP2HcBEZYP3dIfnthUR1h9sMjdCmT/m0CkUZinwVY4ceGkBQsBDnFUvOMz8c+5CF7jkrvmzAKkAV32lSlhos3IF4AjcgBckxhff/DIqiGPRGfVS7ZMAQC83apQe9XRMSsBDt6ht9BYIt2LlLOeEoCWni//LbZC6+nYKDUczAXMenSjbf5SE/ZAudOObNGLGoqJH7zOuKoGfwCFhHj+dr9nKcsQi+6PzlgGAySgBNY2McnKKPkOEe83KkGnLVewIIKrbYheZEiM5a7MYPE0YIHhz4lMuKu2TebvrwA6swDNP6WfoUgrEn9MJNmN8mz4wynJQ0s0Y7hCoSdWGlHxg12dq4dBvO0aD4cegA4yme6sHO5GtiUFUjqnP1OqD/GCMsDP+GJaiyAs7ZXSkEUaCQzUpQ77dPf+1YDwmiAsR754CEqWLFBOcCeS4IrNlDxcBjh1eCIPd4BMldK3xPt7Mz9MXIx2DI5jdW1bQBPkLILscmxIQlR0iH9e/3AQMurFKisYfNGTUUtK1ZJB/cvkbB8BooZ4ooWj8mZRzbA1BLyhbl0g8CI3s75vJ/zFWbaAwki7mrbMsVPtK1bpUCD3VjmDXNb1U800tM4oo88rJ+4Vn5B9RBM0DJU17j5+ULEXUS7VL8lxg==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: backend
    type: Opaque
