---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: backend
spec:
  encryptedData:
    DB_URI: AgBvxNkDVQPRnf4k6+/awVnvksCaIDnkubRF8AK9S6PW3NpvFkUkKbY23Boe6l/RVlIu86Oz6vRCAVAectGfC5Y7Y/b5ZPSB9o/J2FZZBK2NHclUAai+wWGYXVzl1IiZRpR0EdDCl2HWXVpy2RrBNPLlEbWqd+GAInORhpaX+Q1IhP+qXluxP/4YIbY2pxujUstdbSJ1oMQqlr8pi+16ISnp04O8/hv4l7LkGLoZtAhf/2RbnmoRNviU6BqCxPUS/fluN9tBkWE8JB/sEBL246DNrEaIAxBDhEixjMUJ/btTjMxIafuGbsAevmyEI6vdG65BS9KG+nJl/b3RLbDSoVXK1ipyvAVVkFoggrUTFhFrJbFsoGAoGsH7gC57z4xoIHbDekY2uvrEImxJFFPnxfvqGTZX7r1NhMVmO4nHDhGf8FkezbYth0i2vguSsYoj59IN877d02nIcm3BEUP+B6wVX2Qnqk9lXrsFIlzVlVveco+xREZtneyIA8M3lUrUUw0zYXiwpnz+iONj+N5EsnH3j4ndSCoG5baJOpWBIi8hyf+AOl8v65/PoIP+DX3PaGO8fJMPXxmGWILIpm4oAr3XpdL+VDg25XVVkXlPXUp1KaraiPXi+2klALb56HoN6o642Wy98m89Ea7+61zeO60EQVDSS6livxUBdpe+vmZU0OBN9sW0XR3BvTvKPaQ6g5KqIS7iMRvV2amqe8WaJCVtm2LaoGwhPeha8rmTYmcCRb/YimC6IUisHII4ak1nUXyfCONO/lkfsTac71EUzMDCo8geTUhh3ZiGEAkSZ+WfdXZbnA==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: backend
    type: Opaque
