---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: backend
spec:
  encryptedData:
    DB_URI: AgCEP2gVAipnPBirLOoe/X3ZzGZlUxRy605eLx9SoATdImQBjzUvsm2GJsKVWcQGD75/N7dJLvyvmVeX9XFk2zBYQ1x+70lK4esP00cFugiFqyeZ8I+sInn5nLZ5/VpS4m/NvjkXKH/0VdC2BGIg5L+X/sJJ+46qYY7aFx7K3S12Ts3oqu1NwfpVhc27anS2GoN8uD31nJvEzoH2P9R2Nb9eoUIEOIYRUk27zhnhlWsps/Nxvz6NB9WxcXS2mrxDrLUjOaRFsnMuP0cYpN4vGdc42DaESNaMm/wAljgS0MfFPDne4id89Uq25Ae3N72XEbsIr2pGOHQFqfIV572w26mbA6saywGh8a02FH5t9QCfgOvc1zSrhWjzJ/W6xKr7xYJMqc9y6RN8pUTCH5ETFT3H1BMooscZ/NamD7QqDhdFc44E3BGL6GaYoohUpP1KB0IKbAxpwnq/NVuGxMvb3c7XOyPXzYDjs2PY4MJnjwcqHtMfsacF+7hsSDL2Q8JYv9jYsJHh2vQCwTILudiIVZnNkLB5xlPBIzkT+VYtUmy6MfW/N2H8Pef+YfDxda0PrI1TYQo5MySUliOFTyyz1gikWz2horfwzR09dKQJYlkKM7Z9CZe/r9Si7yhisoZtvmaDBygDAwxcbKIiskpgqErlmL6zf0O3bBJ+HTlhpX7WeljrVpKd/I5sBAQW5B+NHt+xzyMuG2/WOeZWXueGTt12Q9DfC22evK7tyZP5tNvy3a/Ux9iyrKG9b9v9fprK5QHJgnqanIsQHqYRA7sT8bfZPBFgyxhnLYpALnfLI1j+IAskTA==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: backend
    type: Opaque
