---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: backend
spec:
  encryptedData:
    DB_URI: AgA9VgPnPy639l/3eBewGsEZEuQpOR9yfSszydRCqb/E22weOz8Xw2PI7Vjox9spd7J/wHEiuNigDTJjDebDX7Rf7jqbhzdn28gevGKSwB5cg6z+EFeamJKiSqvUuL/liS2RMHXECM09CuS3lsH4aFxszJX+1izqW85fak/32OfqbvKWryXDkrfLsOREtPcuj6jLYutMRBN6dduhuxXKL20VECYGq0WN3T3/lUrt1dV1mPOuUlx3FUiIiPG23tNnFOG6AOWGo151Me5ZVWokQBLYeMwtxX2rlvK6TwIWaIF2Pgl6WHTM/7hoCyDziQyaCG+IFioig3YO6RmwRpGX0AwuFnPWNDKnc7kA4AsHc8SuVFTWo2G6UVL3yVF9km8SspWXkTYdyZihncabgW59aFnvRyPvLzt4/v0f064iP9/TenF8SBzoIA1A8//1jmby1Ir/slU4EySpaWNs3pxKRsYF9WQWU4BbDs/NcgSSAHw8Xk0tvLmIsyR6HvZnLfJL4zJmTvJonZweAPfeu6Vjq6mCnHd5Ur0Af03bg0JwXhex0QGfaqS7GE0N807apUD5hwe8+jnrxhJhtGEu9g5TSeu7+yIhSWyng41FG+JIYVPs3nDlSinDICX/5VF7/8hLVCt1PIuCbRFFmshH9oeI5PmwiKOoOUFM3t/2BBEGd3pduwshD6mdeENuC9f69Uq0engERc+BcxzE/Xn4vzYQ3ghViUwnPKzfPLGWgAI00vD5oBKYLKc3bmMRBgCxIsM0z6TzdTZMHoJugo4gIjsCNlkNPMuhY+d2PkaPyeY2xfwqH+W7Wg==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: backend
    type: Opaque
