---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: backend
spec:
  encryptedData:
    DB_URI: AgAPnZUVmQ/83q57DvpXR7wo4cnl2vCSC3Keom3iPUoXrqbvy171LLzhHYvR35EvYfGUHjGN+RXJwOxEQcsJfvuXCK7EJpL4MhtGAwO3hlUK9tk+GNEaCj1MrXuLnvLSJeWTvPsffZj3wqxiw+cYAhM7bvJFpgYMfKBtuYH//CJkcZKs5pSvII8koP0VmOqoGO42v1lTYTucGOP985r7884RQTbPLtnbZN8wwTGtbcf/Cgh6EpbTu+zo/BkMhSBUSPX1qSzM2GQRsovklJ6Xb2eC7BWPOWXcqjRcIEJ1mzfI3n86oeflwJ8Wvd0BUfmoM5rh5D3TU6GQnrO2H4w8N8pzaENdn/bEziFwOxY8rKTB05PyN6OFHyuORxtdqn+dcgkvw30TcYXjUEPIbhcArFdAgvT+V8FcMClTldXgUHBtbm3W/2ymBaJZQBOn3M0s0o0u99UgMcLwPY4fQI26Ov7ThV870Di8g3bFG37iLprhfIyUhTP55hgkvmj1TbixItHK1uShAf4VBDokEGz8hy8url+xL+3NCOP0rR2dbSH/CiibYfANEd3sQZeJSp4WcPX51XQmdVA+OlmR4zNimdBV8aYegPHGbntcS7/FSOlU3RiuvqQNyWaIyZKG5cunM2Ea0kvFPEkuuibknVaBBn8Ec+taVF14fsroFk90/zpwYtjl03Kw16XItBs+pB9e26V5eatvrMCUpWAm3dQszxATa5ilGLe7eq3LiZgpHI5QNEix12wFSmG22+JwP86pgI2nFOjz2hU2iGgqVWPBD5B0LvKuiN0oJ4Ztn3jYMc8X5OC06A==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: backend
    type: Opaque
