---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: backend
spec:
  encryptedData:
    DB_URI: AgCHpvilikDbvzU+vlNXmB0/N+Q69w0QJNe3FY2AQExu4rj5LgtJCCzK6Lb7p/C62EEaU3qbuEcbs/hYg9oYASvxJ2M93KwFRwWWd3wgT1sORBkAfspb/WWXRFe3fS0LFGEJm2rrui7excFFYj8O08fjyK4TbvV5kl640A7qEQzLDAz8DLpaXDKKNvHZ88H2LVYQishiCozdurVUgRbIpDFpZPNR9aUfVYKmry2t58x/NjtOZD+XTnAz5ID2CONDkSreFaMY/4pn9zYyh1nPEpDKKBqBnTtWFCjZ5kR4j/veprJ+pxNPiLJEfhRIa9CX7vCm76ANlgt+se/zgfqeOIoN24k+bna9xbiiY7xwYPo3oSdJL8YYvqNeLb1Ql5sXb5dmUp0csg6pftxeRN6P+55WK4NtZJlNgpMM1chqXFLUhC6+8LifeGZGuybAr8b2uRRmtHt5i2ij+OlPWdUL4ToTH+bQJva3CDWgRaPaPrG3CcCvQCvs2RFp3YdXPeAGmT7yMQyVwb6MEShaUoKMQ1H9Wo2IU6R/IfRxF/Fkr+MUwdNKH78kdj74iiVv0SY9dHy5+dUQbwj7OW4kHJZzKWcGXiF/CgnRIKc9c0d3HH8V3PILDN+XOsQG+AE5dNk+fdeivBrmwQdTUaqh04iHpSP3UlGrz+JbL0dp8eJiX80mhdI33ffKZiYcNmPRXo7Qti+T/L70EAWM1uqWZeYwnC1mFhIrVej+NEhS0Lv5iZDjMIWpLKjQ6Azt8KdzazL8j6/3h7Pz7cJ2kBX7h20vK7lKVL8vRMlWxYeIMfrBdzEdlLBd5A==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: backend
    type: Opaque
