---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: backend
spec:
  encryptedData:
    DB_URI: AgAPkK3lAFbidCIu22o4PyNOCjfGfF4vip8qqC8rgCgqy3JKJyWQxGqznU8kArZeMFN0t01RAtCvPk8B8lQ1QJAkaN1fdKhK59f6QEaaWaDi8CmpGccJVmSdbBZ6HuFb7x+yAiucPhf7o5Lmr46Pk6MzpBXyJ2QHq5qk2uaFWXuYPM4tcF6Mnez53Bwrl/1Y6MI98+w+iv6fg9qYwt0z8eGaA55Tc+8QMUTo+3PHrWRP+cuAsliz/iJKivYYQgeb1exLRgmZT5Il6pk+UaPcUfPxqMvGHnOLIcTyuKRfekgoOSmfvTUyEqQirXfhL8W1MHRkBkCWsoJ7IdJtdATZMlfsGMsFmPXmV1SUugS6UnBuL01dfCGPPalYd0UuJ1IkrtpcpBdC2oIMrns8kcRov4S6TwjK6yCQAdnBncvadBjpMIlAMRIh5heMVUleDtqqdYe1Nf3vQKmIl2kUUKa3tfK5e8YHxleccxlWGWRZwg935z5edNqPlhTcNMEZRVWv/YF6/3Y4zy8xjTcMwdEIpT/RsvkGi94t2ygidtRjGuDr7q0g550OeZz7tnbrztUsA5q+o+hnfqqQ+GLIg/rc7dFtTtNtryWAsLaw93KhAlze6x06hr7eW7hiWSzAPIIViupLQ2EqR6btYD17fdgRsqASikia1dLzjjaGggXoiugxlTxtbkMYicqQZMfkFfBjtHE59rtSizmeoQvWHlqHqIqPgmaVXGiNO2Sq0x4kqxCZ0pg6O2ugmFSPxhV1e7FW8Pjr+nVD8fXK7DTa2VM83bDDJMdyUacZ1fs4R8vQYmsPh2yJDg==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: backend
    type: Opaque
