---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: backend
spec:
  encryptedData:
    DB_URI: AgAEQDh9mctnMI0QFu7AurGBCg0pZ3g8js/PrbAhSY9Q/F/qFDLWEw/ORTMbOvWMaZdsPsuhIS38xtGTwQIrPy3NKDzNdcyFoOC+vNXs6N+iPmZWYJXM4jMDGPQOq7zKwjwOTCLSYN8rMLgKCS7c5fAb9asyvZT9mNVn5Pf2FDaRTCGOtc0fCs8bsIOZevakUgGQ+2pJ7RanEuE908UtQk/tXYBntU9mgRXKzf+FDN6h6I+XAPxYqI/hm8BrN6fJNDZX0n4cn4LRCE+orjRKNYm8SzJ1tiWDG3wHmiJhaHJd1M8hHeGKDflv8FlOsiYXQS2UxB+PkUGzyNHFyix/rPaRyN5E4bZzqxMkEXhFq2AFD427ea5JC8CRIcbCG4ir7V5eOYVjpts8BtPcXwXBsZn0WHfbaek1kGNwAfGyomiaFLVoAzkelsvYMxs0nVieOg8nsgsYnyh38ZM97beGmdD1oDC4ve8S7v80hvNNq+S1z6bt58GfL1ke5aBIbR5eYY6E1GM84Gi33OZDt1diW6yyoPkW3UW3yLQc4naURqQnt+kzEzzOn2RZFtqbRxkkeRuS5Oz6PB0m0xCSWG0wyURfzhmT3p7kUozwfjZHjz/OD5oyj1sM7Q9QVq08Orp1f7oZFLGUlANygD4E9BOUrR6MKoN6EJuuJMc2hOdUSqeGf68URo6I0vQARFdQ5QJAx1JH57jnc9xTpCwqB6fkv1+9vPrJCDWTnd5hK4GVf1rpZ8MLLjVvd3uInqtledecWTm5qAXb66QjjobMUXu1BxGmNXvRu0wETrTwK5w0xH5PVE4QEw==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: backend
    type: Opaque
