apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newsapp-pgadmin-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/depends-on: '["sealed-secrets-controller"]'
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: newsapp-dev
  source:
    repoURL: https://helm.runix.net
    chart: pgadmin4
    targetRevision: 1.48.0
    helm:
      releaseName: pgadmin-dev
      values: |
        replicaCount: 1

        image:
          repository: dpage/pgadmin4
          tag: "9.8"
          pullPolicy: IfNotPresent

        service:
          type: ClusterIP
          port: 80

        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: "nginx"
          hosts:
            - host: pgadmin-dev.weblightenment.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: pgadmin-dev-tls
              hosts:
                - pgadmin-dev.weblightenment.com
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 768Mi
        startupProbe:
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 20

        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        existingSecret: pgadmin-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
