# clusters/dev/apps/pgadmin-networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pgadmin-allow-ingress-from-ingress-nginx
  namespace: development
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pgadmin
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  egress:
    # allow DNS and TLS if needed
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # allow connection to DB pod(s) in development namespace:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: development
          podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: 5432
