apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newsapp-pgadmin-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/depends-on: '["sealed-secrets-controller"]'
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: newsapp-dev
  source:
    repoURL: https://helm.runix.net
    chart: pgadmin4
    targetRevision: 1.50.0
    helm:
      releaseName: pgadmin-dev
      values: |
        replicaCount: 1
        image:
          repository: dpage/pgadmin4
          tag: "9.8"
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: 80
          # targetPort usually 80 inside the container
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: "nginx"
            # optional: limit access by IP range
            # nginx.ingress.kubernetes.io/whitelist-source-range: "x.x.x.x/32,y.y.y.y/32"
          hosts:
            - host: pgadmin-dev.weblightenment.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: pgadmin-dev-tls
              hosts:
                - pgadmin-dev.weblightenment.com
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        # tell chart to load UI admin creds from an existing secret (see notes)
        existingSecret: pgadmin-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
