{{- /*
Network policies for backend.
Each resource is guarded by its own conditional so rendered YAML stays valid.
*/ -}}

{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: be-ingress-from-fe
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: frontend
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
{{- end }}

{{- if .Values.networkPolicy.backendEgressWeb.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: be-egress-web
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: backend
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            {{- if .Values.networkPolicy.backendEgressWeb.exceptCidrs }}
            except:
            {{- range $cidr := .Values.networkPolicy.backendEgressWeb.exceptCidrs }}
              - {{ $cidr | quote }}
            {{- end }}
            {{- end }}
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
        {{- range $p := (.Values.networkPolicy.backendEgressWeb.ports | default (list 80 443)) }}
        - protocol: TCP
          port: {{ $p }}
        {{- end }}
{{- end }}

{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.backendEgressDb.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: be-egress-to-db
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: backend
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
{{- with .Values.networkPolicy.backendEgressDb.dbSelector }}
{{ toYaml . | nindent 12 }}
{{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.backendEgressDb.dbPort }}
{{- end }}
