# values/memcache/dev.yaml
nameOverride: memcache-dev
replicaCount: 1

nodeSelector:
  role: application

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi