# values/memcache/prod.yaml
nameOverride: memcache-prod
replicaCount: 2 # Higher availability for prod

# Spread replicas across different nodes
podAntiAffinityPreset: "hard"

nodeSelector:
  role: application

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi