apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-db-prod
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/oci/db/prod
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values: ["database"]