---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    DB_URI: AgCoxFl9MAg57hCiETUVSOWRrGYQ7t981m2bKGnQJomPEO0GFA3gYUbcpj8xczmGNSuf/sRf+9Px1NHg88ZrbEMHYOArgHDv1KtFn0r1B0pZZrEZIqrQcNWZpYOYnY93WadntH7E7Eo01Myw99SyPq/uC4uJaqoCrKRlp057AGwkg7seAJdEBCK3Y/Zt7W3TunYlyrLyPkyjv+kvXweFNmK8p2E3ZS4PpRjgwDj5I1OJzcLkiy9PN1eQrxcMgvimdA5e60r/SfhfivFP7v+i667SoOgIJadzKOWFNGDr6reHISEfp3e959Pu1VctS+pAfVWGbahRZbB5N8w6kvjYHZFC41EFo781Kd/ztblFX5tdx5cGTmXXNAsnYaQ63XtAthxOLnhHnKJqMWw93WnahpWM8Iw6edYCoX7M/zfGqcX+azfcUjdWQf2fMP+/hQkefW9QjdwpEa7P/LrsbJ71U8ddne64HYJOJ19nQsFz/KjXFz6jyF9ed0+DRsqPmpqYnWCaBQiP/fZDeA1yK/bA6loM3snfgsgJwj2f2FWVqdj/45xx/0S6tURJ6YcNt4n6QT4pofe3g1/BDAkb8Ty9Bl5NhnfoUEZERxOhxv2ew2FJtxghmLe4uqZiUjkY0/fLs3gwdj+joZwEw9uGz0BftK8bMw7urcNmklQzajSV7nbVQC5pT7vcfL0T3MX5JdErxw2QA6Faf7RETjPTwh2shUwb8tOLPDLBV1kEVH4nKTepXUuoEmCZ0WMKLAr/tc6RJEeNmU3m8syLL6QCHQddAPC/WxfVmBqS+X16r21JcSK/3BzY+5np85XaIA6d7cc=
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
