---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    DB_URI: AgCQ8kNHX5jlO0CU/D2+NNr5hYUd5M9NrN9nbBO2GQt6YA1rm9TvSb1vSE8LHDTx1/7crJa11HT2sAFnMbIeSe9wdFyxXjY0jLAEeEnJ7GVtA2mGhp7oCVu8s7i4GbsI9tHIdxt2oaicqmwA/eUlXAI1CR7i7MxkOsGjtE2DEZ2JdAr1PIvpPRyw7w+Je4PCJg7zjuK6bHBdScXaHdqBwW+cRQwFZV0g31MD8/WATRniLV+ZEiHNisAlF4iHyjtSV2OJe53objFUxkfbbKF9W4fPZ57qe/aWdDhJBDc0aX2WTF2lbN5pbUljtIwLqUFGvVKbVitUNyLjC4C6hhKW4HZXVL/6UyMRl2AVsvh3OjeQSlr8poXcYXOLtY+kPKNU6D3pEYq9tBg8WfwpZ5KtewYp/0EExQP+lM6FGYZqIIqJ/mR7zRg87Uzp4/QhBS7fY205Ez7kssnCx5CCInwOU0rWcR7i37Gk/BlB43lGSOQPH9AXOWoucJV1ceetXesxpv0wQPKxrFrD7n/mEj2DMn57UUlfy6qNf0YGsMRoth+rkHjLIaQpLkepv6AYxCqgNlMlaIjGz4z8porJotyEhP8ADawFUjDtw+vSZkWnkW4tYL+XkjKDdJVNUGnjLH/jgePJunGI2v9UmBPBNp5iQHAY5Hdr31LFcuDbcVBr2SjOFvp00wy1ZuIZHLck27nscpoxtfIQiHpaF/yQaLquFj6eDZ97oLH4ZA6CMscEAvwCDA5obRnoTCgJUbo/h5ox3FHI+qg7YRE2qz4AfQdxU1o8y6YHsIzKlXC3F0iVt5pOBzgmqOmOeeA/3W0lSY4=
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
