---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    DB_URI: AgAf/wtJJqb3MiwUVtjedsZuCTPlhH8KXXied/SKeLUlbzQC68ViGMv8tNMbXweXeae3ug9iegZPDEuHQ753xZMYprZfaXuoRcIxHKid7fBLtjpM5eHWtKUvSkjygSMBTxna93IGaWQT/jDjozSyQ222AsdiQ+rKKNqrC05pT1kSnbNiFHQhKhTweZ4Q1ZCocUSa1puAUPgYz80cStXunKvW17iMnOkEu8Lj5ausC3Scltxcm0CygRtreYP1ZSb5L5qPPsLsN+333VHbEzTp17SZ7HL2KT9keAdpXjJuIADeSAk3UkQmoCHbijCY+xA8QH6aQW6lBi8lE1pv3dxmIu8uc3lDCr6FY3OWOe9S9K8TSk++QS/RH7AN1m7T96hT9AlSfA2sI41+F0bW0jfhal2O0TTGhPqNq/mnFQ2qCyrIqaJYV9OQsrMKX7UlvABwI7fy6XXcXNQQYNbxxl4LySHHQSUx/Zr7WR0yhFqk1mR6PSxUy6WqLQaO6MR/v9tdR3VOPc8QnCQmBWPKOHCVc0rVBflbUZoi8EHQCP1yc5UY/NtIsZZRwZ7VEuzzY0h1CFPI4cqA920bY+9riQCT0HCIUikLMjIWN1ytynIF506c3+3iru301JcSmqn+wgEfnwGi46XP0wuCLqyltrjFmqI6llhL20JFjXsdrHnFt1mtGv4KAmdE3V/VC+Ja43JKzqWnMV7VXc3DLnowhRWu6MmniTWdTfrIod+xi6DiXEa28LoQjL2wq5nu6w64GlhssIvT4FsgAZ6KNOU3SK9eHfI4/xCv8i/aU5eTK9jLimrBOu11tw==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
