---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    DB_URI: AgBhz2Z31ghV6mbVyLCiQX9bll7TvkcxpmPFG/uZBP25NdpzRN8SVYlrahQFO/J642rJ6N2iPfh0/rWP5DSfmIrIqv1mhIivDPZTQasDSvmImJSi+m7RfRSDNZAi0YCBFeWKVhZvMbwhgJ/ygDS1DWtmja5I5e8Kax/oUuhF2wRjQLnnoI+oa62kuk0bftDNsQTyq+1fA9WAsf3KvdSB/ZD1a9Xm1N17Q1xb3UZOoR3cGrwma2hLi793u/lvQQ4jRmgU8lIdhsVL6jILnA583AsuUJ4LFSulzgj/mV5UZn9kjcBfhJs53ol1aoKVDcyVyvRDgTJeveQMTrHqWkyMLVEwOaDRx/nBMK2te2zD7Lm/XRKOKOyPCAxS1q0n3IsCrx0jgNgAOPKOM8EqHL6FMSJbBhQ/ygGZp/i6fgw2dkQCH60E/YFwMED4+INH2YNq4Rc5K3sZ/jY8MPbD+qMAzwTS+PYPQ/96y/1gu7yL4Dul7ysXac7hgzPO6MCl3DdESUn5sGyJrJ39+xZmt5hRAz0RqcrlzS39hbDPKsy1HQU86dViAm8hWtDIGc972HuwSD4rIl57c8gyeWUUrhXpUEULJzXpAn3ZRHQ7EnV/HKToIuPY5KYW+AGkVYcV4re2sglBp1dr6VU8iz1/Hqx9A7d7ifhFO8+505zeQwJ/JzsX2T8DfXnXEcTlX/zCVTEsxjhFeTIOJfS7QF97SN0jcIlPV0WE+MK8UTyGb1geaMacKNsLNBi2X2+Qet4eeBl0+Q8YZch+MdTr8I9XkIUiRds395Bb/0/vXd3cZjn/1jF6A1lC8kY1ih9EorUvWy4=
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
