---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    DB_URI: AgBSKkfqs82bXDXWBn3G75DpNQl8xkKM/AK4FbQYeO5quZ1/u7qAq0sU4x/umjqk9iicvLJKtUshVSPRxLCUf880jYks+f56laWuBsnEHMi9Eg8D6umqwdpF8Yf7j5Awvf3bMuUbHULKnuLduNX+w9pyZMbAK0Fg02+dnRgqU2FxeVZ6gR2RPnnY0L8JUta2tXed600MiShNHjcq/WLmYkiwEPMesnVdQWmNlUnenNwMBj24RNV0Pmbrv5VqX0U0LoSjsArmzazWjr+4LptiMt98Yno9DJ3gc7wIPwksQwA1KygPYW5qboqKpxsseHMeZWDzaYN8ot/NTJYRS1n1VFu2V4/jSAXtaQYKaHim2NrgGvdwD8CcDivJayA2Jbey04Mtw0OjFXMapZME9EKVmyXqMdu6QaAHmcEGbWFDoINZrMbj34QpF9tI+7cftoM6mHKYYaM0VA+HFmaLra0vZXUqYpGqEkSLH4YQEzi0x1nWmzgid+p4OAyskavmfRzm33Nf911igu5oq8JhOPqytfuSuq7A+m63JX3Ovrjrv5LpE6z0TKsC1bG8Uu3BhDbDfttA6E2XvnaAy5LK8ZLnzO0s7eyzl8MyHGyKKqOpnp9e8/CyWVEvgg/1YYqJRNIdSvfo2QVKv8C9jXFZJQIPjcyb3cznsE5KLjPz6bzgNHB2PCeHR4nIjLM7LGMqn20LvdkR9xJSbvHgfBaGcSQd8MrqtSa+1hl5sS065ASA9qLZGVDZa3dUwmv72iqqpuSyNKIHm+tuxxQrMdEnedPuCNrHOREfMhS44TxIcGbXAB/6Np5hQueQz3aOQCc5Y4g=
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
