---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    DB_URI: AgA+4X1LLJS0Xudka5pnpl3aL7WjLofOTek64e24lqQPG7rmmt1X/9kVFONe88Kb/CuibNwGv/V6ledSkRA8OHNumq7V+IQIv9PjikKPR3ug0s6kQtlFTCHnS0TAtKgf7+omYJgMk/DR7YCGfY/QFnu/j+uogwVUFTaQCa2CYu8851BPZTz9L+Vy2cWLOg4RaZeYejVceeO/L6SSJ2aZbF1gcs5yZekXBo6Z7THedm1+d1IDT9LGzS9i6k73l/Dzfg8bNxeOpqOsPGxKTUObwbZdBmM1jYgx7wYpr5Trwy89VpspJxNTTbnmlinz6d8eX4xalZJWfFPukfP3uAci3qvxvgW+r29mZq+Y/Rwv3E0UOwqAVZToXarcGXaDiPI2AU7WndrzLrdQsOFG+R6p6wvfSHXg/onE4eEHHvua50TAzhyoIAxRYDWDbsOqRYTXHMBLuF+nYSWVli1LZ01EwCg9cXFq+ONBTwnklxU13+JMnGG3dOEB//xewDIMArI7iUVk3qyqmE1NTG6JkSlreAtoP6rDjk+hIx305yniz6daLjGxU+CH/+RzpLSzqcBdSpLP7zAGkp24+j+96Hq13xqxG4rbnDUMun3NqKWcDz9aCvU8u7l3zeOMMMxgGD7F+kk6TNoq52/ZIcRIiehvT1nUND8s5b3W4xFxryPbC05ZWiXmwWU/AcD/yaaGhcWXKAf16GeilV+GIiNWbmiO/bNCUGzTPb+hTIEYcsXD81Iw/U3I0OA8GssjRVXc+D+6Mq1lMZrCK6Z4q1M+3ZiYen/4Sn14Fh0ViKRKeusfOdDBvEQtugmYQF7/nZHh2Jc=
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
