---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    DB_URI: AgCEFhOFEMXGRE9/YsWMcIpgcvRRUWfuFMrHTq0Rn1o0PZQT7FcgngRi3JKZzkOu5eSWXC9C6zphaDNTWDjLZoQvHfYy4rttVNGLyGU4cWc4qaIAcQi++LWBYMl0hs9txxSe0IVj6AK2Rz1VHG6bvGhZj9n7vbjPg+x8400wAmxt8huiDUfB+uLwgavxwAPG04R9yAkXmMnvUFipt2OkJauNi67ebJflXcichgMzhIa8gDnFwxco3eUEvpsrKBSQnXPW8xDRlerd4oaOqe9+R2ft+Gw02SCTCLyqf1a16nd7FDORno06oA58IS/cbSAvhPgoUA+TdbJxp75HE6aXMoUOHgHFt+tqgYScsCjMRpjNv1yeJGYyTgB9FGrj52GeiohMRc65Iitq3YZO+MWgdo0yyfrHwVGbIv/GQPF9vn+o2y4vTa2d8S+oE4+EXvAIX+aHYz9ENVwBj+P9ZxapgE1oESp2cmUitz//luqnayNTL+8Q1nOAf2MrLPK3Sahn8Bn8mQmUI/uD0oRxn0lumArmbwKuYEuQ0DwsTc7m+mEDne8aDsab2fW9pTn/tW1n9fdP8RyGGkW1VYe3jOFyVNucTWjP0F27ZgM2LPwDPl778JZbPrMNv97d6wiXBPOLKiW/iNO0wt7Rhl7S8KvkH4qEKMIWGCz5kKePjbIRm1d/+1wKSuU76zqv8ILvK+BOgO7vLNLbxgWhmseu2guCgI3C7/McVkE5XReqllSuEDXzsHBznr9fZcQhSlbZOHHvttciMCEz/itWhN9iYHR/eCXTxYSWCCxz6Je/Jvitt7E/P4L6tQ==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
