---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    DB_URI: AgAL3DNGXYxSwNx2JQq6Rjr5EPWA3bDbuD0uIchff5oFbWoZG1aN1jFCylCcJj3WIsxTvTdn0mTVDqJN7/tgSqzi8ZtCUAwFvpQk6bkWaPjmmH/RJcYt446prnPpJYJRTrMzQ4wT8L9SalZ/3AEpsn7ZxwUReLyLSgrd8yFAT31pLjiW7qHw4sPUl40Bvf40RPykVhveP6PkpKy75NID/5Dtg+ILjBGyiqmT5JO1RCdf/QLbkS2yvN5j15nGG5YGky7r1MQeLg9JN9kEy8zgMhnm380G4zYq9k87V7VXVwGwgTcIsZwGVyHJsrZoLxWlGA9m8YAMkn+m3W8WTu9LLOIAZYJmBkxTzbKqnvkzCQ/nOCSHCgjAOdeyaTB6iYvxiQNvwaWQUUB1/A5JmqSokKGQ22xkfqssVu9bVzstr3iZi2r/qo6wq2V2m/BZhFWtIoSkniBzu6tXoEJ9nI7etWT6h6udQ5+DyN15upzs4zAr9MbUgcCDos6AGAVSF89EWaV1QImetUJy3klTPh6gv/sy0JT0aoA8yowBGZd8WPne2F4YmzYJzsU5uAfeQcJnHmPoSSPyTOj2MQ1mU1NIrxdqYZOyysdXn8fKr9Vt9+cHyg5yX/iI1KhiW2vdawVAKMJ/bjgxqZ3lILFv3R0MK/Y7wzVEyvAzN1KBNeGwAcQThkGloDK5u2xImM5NgIidpPwcYQtXXt6RiFutymKNhB7/s7wJV4/ltG5xIG/ZlDI/NFv7UFd426QeyG9IJ84e8ELGTavq49MvOiEOqBEozlVn2Us3p+vzwZ8oQYt0WLp0OaK7vg==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
