---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    DB_URI: AgCEwILBcpVNBs+lfNBbJTWaf9GR/bOEnOpume/z7chxIvBwEe2Ne/oQBUo3pgiriw0CT48Cpo/iCNB9cupkAz4/qJQbVkyN3B/sZuSZlEazJskjlJcV+X0iTBr4Sakf76i/o46yofH6zvSFan5+86sufW5hnN3VT6CWhA12rv3UOkvO8R8GY6Y1s/M/kxsiWYWjqnRLarAe8QJcy2Z9y2fKb0HbUI3KiwHn9FODq1WfpjGm7HxgUnbX/Xmn4updhhKu49UFd7L7HfT79F4O9nju88074MBGUQIQX2MtgbecwhPt9z7GNl3MTfqbNVL32M9y/9y+xEbDTsIIbc0zPVbqTkYtsm/rgfQGOW1cwIjnCPXNPaqwfmT+3MM8b4802BhfrqUPxcH+T2hAMMmoFiUFe7vVGkbGKvUBRVeYQOIoX/JiHOn4/T1qn+QMVeJFFM+uIeSbgu+USsPESJrVUYjMGw3IORSZji3ZfdC3WCvMIKs5g77gZ59agDDr1a1e6tAqY15zwipwNlrRco1sgpuPOxOBkIuh9nvkaHi/gZC81ao1PGroic0oZvVi/c4ms4H+wv08HP8sjdxgg2nbRl8gViYM7l+MWmVI77//LK3FDlYVH6okUPQYmeABeTLRtMA6n7p4z51TLv0x+HDGxP1w7X1vFPMGJO/jbXSQArHHU3h95lnAXr7W+TjjNJjKWHRBQ0qJQtcrJ381HVm0EGZbPXwQpn1uUMv9Fnz8X+bU6oxvQ/7nyo0qHpRBV0RvjxbaPdZsdHC09GtUuw6UqgJ2f0Oyi3Mr67BDIZSPJEu5FWig8w==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
