apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-certmgr-tls-egress
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-95"
spec:
  podSelector: {}
  policyTypes:
    - Egress
egress:
  - to:
      - ipBlock:
          cidr: 0.0.0.0/0
    ports:
      - protocol: TCP
        port: 443
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53
  - to:
      - ipBlock:
          cidr: 10.43.0.0/16  # Cluster service range
    ports:
      - protocol: TCP
        port: 443  # API
