{{- $root := . -}}
{{- if and (hasKey $root.Values "ingress") (not (empty $root.Values.ingress)) $root.Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" $root }}
  annotations:
    {{- if $root.Values.ingress.annotations }}
{{ toYaml $root.Values.ingress.annotations | nindent 4 }}
    {{- end }}
    {{- if $root.Values.ingress.certManagerClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ $root.Values.ingress.certManagerClusterIssuer | quote }}
    {{- end }}
spec:
  {{- with $root.Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
    {{- range $host := $root.Values.ingress.hosts }}
    - host: {{ $host.host | quote }}
      http:
        paths:
          {{- range $p := $host.paths }}
          - path: {{ $p.path | quote }}
            pathType: {{ $p.pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ include "app.fullname" $root }}
                port:
                  number: {{ $root.Values.service.port }}
          {{- end }}
    {{- end }}
  {{- with $root.Values.ingress.tls }}
  tls:
{{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
