# Cert for ArgoCD
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-argocd-weblightenment-com
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/depends-on: '["cert-manager-helm"]'
spec:
  secretName: argocd-tls
  dnsNames:
    - argocd.weblightenment.com
  issuerRef:
    name: letsencrypt-dns01-cloudflare
    kind: ClusterIssuer
---
# Cert for frontend (prod)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-newsapp-weblightenment-com
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/depends-on: '["sealed-secrets-controller","cert-manager-helm"]'
spec:
  secretName: newsapp-tls
  dnsNames:
    - newsapp.weblightenment.com
  issuerRef:
    name: letsencrypt-dns01-cloudflare
    kind: ClusterIssuer
---
# Cert for frontend (dev)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-newsapp-dev-weblightenment-com
  namespace: development
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/depends-on: '["cert-manager-helm"]'
spec:
  secretName: newsapp-dev-tls
  dnsNames:
    - newsapp-dev.weblightenment.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
# Cert for db (dev)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-newsapp-db-dev-weblightenment-com
  namespace: development
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/depends-on: '["cert-manager-helm"]'
spec:
  secretName: newsapp-db-dev-tls
  dnsNames:
    - dbdev.weblightenment.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
# Cert for db (prod)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-newsapp-db-prod-weblightenment-com
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/depends-on: '["cert-manager-helm"]'
spec:
  secretName: newsapp-db-prod-tls
  dnsNames:
    - dbprod.weblightenment.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
### Cert for pgadmin (dev)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-pgadmin-dev-weblightenment-com
  namespace: development
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/depends-on: '["cert-manager-helm"]'
spec:
  secretName: pgadmin-dev-tls
  dnsNames:
    - pgadmin-dev.weblightenment.com
  issuerRef:
    name: letsencrypt-dns01-cloudflare
    kind: ClusterIssuer
---
### Cert for Grafana
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-grafana-weblightenment-com
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/depends-on: '["cert-manager-helm"]'
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.weblightenment.com
  issuerRef:
    name: letsencrypt-dns01-cloudflare
    kind: ClusterIssuer
---
### Cert for Website-dev
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-website-dev-weblightenment-com
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/depends-on: '["cert-manager-helm"]'
spec:
  secretName: website-dev-tls
  dnsNames:
    - website-dev.weblightenment.com
  issuerRef:
    name: letsencrypt-dns01-cloudflare
    kind: ClusterIssuer
---
### Cert for Website-prod
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-website-prod-weblightenment-com
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/depends-on: '["cert-manager-helm"]'
spec:
  secretName: website-prod-tls
  dnsNames:
    - website-prod.weblightenment.com
  issuerRef:
    name: letsencrypt-dns01-cloudflare
    kind: ClusterIssuer


