# addons/cert-manager/issuers.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-cloudflare
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  acme:
    # production Let's Encrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contact@weblightenment.com
    privateKeySecretRef:
      name: letsencrypt-dns01-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  acme:
    # staging endpoint — use this for dev/testing to avoid production rate limits
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: contact@weblightenment.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
