# addons/cert-manager/issuers.yaml
# Self-signed issuer for hands-free origin certs in dev/prod + ArgoCD
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selfSigned: {}