apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-cloudflare
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  acme:
    # production: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contact@weblightenment.com
    privateKeySecretRef:
      name: letsencrypt-dns01-account-key
    solvers:
      - dns01:
          cloudflare:
            # cert-manager will read the API token from the secret below
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
