apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-certmgr-tls-egress
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-95"
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
