{{- /*
Creates a path-based Ingress for the frontend, accessible via the LB IP.
This is separate from the main host-based ingress.
*/ -}}
{{- if .Values.frontend.pathIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" .Subcharts.frontend }}-path
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- if .Values.frontend.ingress.certManagerClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.frontend.ingress.certManagerClusterIssuer | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    - secretName: {{ include "app.fullname" .Subcharts.frontend }}-path-selfsigned-tls
  rules:
    - http:
        paths:
          - path: {{ .Values.frontend.pathIngress.path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                # This now reliably finds the frontend service name
                name: {{ include "app.fullname" .Subcharts.frontend }}
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
