{{- /*
Creates a path-based Ingress for the frontend, accessible via the LB IP.
This template computes the frontend subchart fullname reliably (works even if
the frontend subchart provides name/fullname overrides).
*/ -}}

{{- if .Values.frontend.pathIngress.enabled }}
{{- $sc := index .Subcharts "frontend" -}}

{{- /* Fallback to a sane name if subchart info missing */ -}}
{{- if not $sc }}
{{-   $_subName := "frontend" -}}
{{-   $_fullname := printf "%s-%s" .Release.Name $_subName | trunc 63 | trimSuffix "-" -}}
{{- else }}
{{-   /* Determine the subchart "base name": Values.fullnameOverride OR Values.nameOverride OR Chart.Name */ -}}
{{-   $baseName := (or $sc.Values.fullnameOverride $sc.Values.nameOverride $sc.Chart.Name) -}}
{{-   /* Build the fullname matching the app chart helper logic */ -}}
{{-   $_fullname := printf "%s-%s" .Release.Name $baseName | trunc 63 | trimSuffix "-" -}}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $_fullname }}-path
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- if .Values.frontend.ingress.certManagerClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.frontend.ingress.certManagerClusterIssuer | quote }}
    {{- end }}
spec:
  ingressClassName: {{ default "nginx" .Values.frontend.ingress.className | quote }}
  tls:
    - secretName: {{ printf "%s-path-selfsigned-tls" $_fullname | quote }}
  rules:
    - http:
        paths:
          - path: {{ .Values.frontend.pathIngress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $_fullname }}
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
