# values/pgpool/dev.yaml

# Create a service with the *original* postgresql client service name.
# Your backend app is configured via SealedSecrets to use "postgresql-dev-client".
service:
  name: postgresql-dev-client

# Give the Pgpool-II StatefulSet a unique name.
nameOverride: pgpool-dev
replicaCount: 1

nodeSelector:
  role: application

# Point Pgpool-II to the newly renamed internal PostgreSQL service.
backend:
  hostname: "postgresql-dev-internal.development.svc.cluster.local"
  ports:
    - 5432

# Configure Pgpool-II to use the same credentials as your backend app.
# Your setup uses a secret named 'postgres-credentials'.
postgresql:
  username: "postgres"
  passwordSecret: "postgres-credentials"
  passwordSecretKey: "POSTGRES_PASSWORD"
  
# Enable query caching.
caching:
  enabled: true
memoryCaching: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi