# values/pgpool/prod.yaml

# Create a service with the *original* postgresql client service name.
# Your backend app is configured via SealedSecrets to use "postgresql-prod-client".
service:
  name: postgresql-prod-client

# Give the Pgpool-II StatefulSet a unique name.
nameOverride: pgpool-prod
replicaCount: 2

nodeSelector:
  role: application

# Point Pgpool-II to the newly renamed internal PostgreSQL service in the default namespace.
backend:
  hostname: "postgresql-prod-internal.default.svc.cluster.local"
  ports:
    - 5432

# Configure Pgpool-II to use the same credentials as your backend app.
# Your setup uses a secret named 'postgres-credentials'.
postgresql:
  username: "postgres"
  passwordSecret: "postgres-credentials"
  passwordSecretKey: "POSTGRES_PASSWORD"
  
# Enable query caching.
caching:
  enabled: true
memoryCaching: true

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi