image:
  repository: postgres
  tag: "17-alpine"
  pullPolicy: IfNotPresent

# Service and naming
service:
  name: postgresql        # override per env: postgresql-dev / postgresql-prod
  port: 5432
  type: ClusterIP

# Storage (uses cluster default StorageClass when empty)
storage:
  size: 10Gi
  storageClassName: ""    # e.g. "local-path" for K3s; leave empty to use default

# Container resources (override per env if needed)
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

# Pod-level security context (helps with volume permissions)
securityContext:
  runAsUser: 999
  fsGroup: 999

# Init-container helper to fix ownership of mounted PV (enabled by default)
initFixPermissions:
  enabled: true
  image: busybox:1.36
  runAsUser: 0     # run init container as root so chown can change host dir perms
  ownerUid: 999
  ownerGid: 999
  chownPath: /var/lib/postgresql/data

# Use credentials from an existing Secret created by bootstrap:
existingSecret:
  name: postgres-credentials   # must exist in the namespace
  userKey: POSTGRES_USER
  passwordKey: POSTGRES_PASSWORD

# Name of the application database to create
dbName: appdb

nodeSelector: {}
tolerations: []
