# backend defaults
app:
  name: backend
  syncWave: "1"

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

# Pod-level securityContext defaults (can be overridden per-env)
podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

# Container-level securityContext defaults (can be overridden per-env)
containerSecurityContext:
  runAsUser: 1000
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

imagePullSecrets: []

env:
  plain: {}
  secretRef: ""
  configRef: ""
  secretRefs: []

hpa:
  enabled: false

probes:
  readiness:
    enabled: true
    type: http
    path: /healthz
    scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

  liveness:
    enabled: true
    type: http
    path: /healthz
    scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 6

  startup:
    enabled: false
    type: http
    path: /healthz
    scheme: HTTP
    periodSeconds: 5
    failureThreshold: 30

networkPolicy:
  enabled: true
  backendEgressWeb:
    enabled: true
    exceptCidrs: []
    ports: [80, 443]

  backendEgressDb:
      enabled: true
      dbSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
      dbPort: 5432

# --------- Ephemeral persistence (emptyDir) configuration ----------
persistence:
  enabled: false             # set true to create the emptyDir mount in pod
  type: emptyDir             # only "emptyDir" supported by this chart snippet
  mountPath: /app/uploads    # <<< default set to path the app expects
  # chown settings are not required with chmod approach but kept for backward compat
  chown:
    enabled: false
    uid: 1000
    gid: 1000
    runAsUser: 0
