probes:
  readiness:
    enabled: true
    type: http
    path: /healthz
    scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

  liveness:
    enabled: true
    type: http
    path: /healthz
    scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 6

  startup:
    enabled: false
    type: http
    path: /healthz
    scheme: HTTP
    periodSeconds: 5
    failureThreshold: 30

networkPolicy:
  backendEgressWeb:
    enabled: true
    exceptCidrs: []
    ports: [80, 443]
