apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: mysql
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: 3306
