apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default (include "mysql.fullname" .) }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
