apiVersion: v2
name: newsapp
description: Umbrella chart for frontend + backend + postgresql
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: app
    alias: backend
    repository: "file://../app"
    version: "0.1.0"
  - name: app
    alias: frontend
    repository: "file://../app"
    version: "0.1.0"
  - name: postgresql
    repository: "file://../postgresql"
    version: "0.1.0"
