apiVersion: batch/v1
kind: Job
metadata:
  name: cert-manager-webhook-ca-check
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: certmgr-webhook-check
      containers:
      - name: check
        image: bitnami/kubectl:latest
        command:
          - sh
          - -c
          - |
            set -e
            # try for ~5 minutes (30 * 10s)
            for i in $(seq 1 30); do
              CA=$(kubectl get mutatingwebhookconfiguration cert-manager-webhook -o jsonpath='{.webhooks[*].clientConfig.caBundle}' 2>/dev/null || true)
              if [ -n "$CA" ]; then
                echo "caBundle present"
                exit 0
              fi
              echo "waiting for caBundle... ($i/30)"
              sleep 10
            done
            echo "ERROR: caBundle missing after timeout"
            kubectl get mutatingwebhookconfiguration cert-manager-webhook -o yaml || true
            exit 1
      restartPolicy: Never
