apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  namespace: argocd
spec:
  project: newsapp
  source:
    repoURL: https://github.com/eli-pavlov/newsapp-manifests.git
    targetRevision: main
    path: charts/frontend
    helm:
      valueFiles:
        - ../../values/frontend/prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
