apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newsapp-frontend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eli-pavlov/newsapp-manifests.git
    targetRevision: main
    path: charts/frontend
    helm:
      valueFiles:
        - ../../values/frontend/prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
