apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.2
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          kind: DaemonSet
          ingressClassByName: true
          ingressClassResource:
            name: nginx
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
            externalTrafficPolicy: Local
          nodeSelector:
            role: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
