# clusters/prod/apps/memcache-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memcache-prod
  namespace: argocd
  annotations:
    # Deploy after the DB but before the backend app
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: newsapp-prod
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: memcached
    targetRevision: 6.6.4
    helm:
      valueFiles:
        - ../../values/memcache/prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true