# clusters/prod/apps/nginx-db-proxy-prod.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  # FIX: Target the 'default' (production) namespace
  name: nginx-pg-proxy-config
  namespace: default
  annotations:
    # FIX: Ensure proxy deploys after the database service is created
    argocd.argoproj.io/sync-wave: "0"
data:
  # FIX: Use a resolver for runtime DNS resolution to avoid startup race conditions
  nginx.conf: |
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    stream {
      # Use Kubernetes's internal DNS resolver
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;

      # FIX: Point to the correct production PostgreSQL service FQDN
      set $pg_backend "postgresql-prod.default.svc.cluster.local:5432";

      server {
        # Listen for SSL connections on port 5433
        listen 5433 ssl;
        ssl_certificate /etc/nginx/tls/dbprod/tls.crt;
        ssl_certificate_key /etc/nginx/tls/dbprod/tls.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Use the variable for runtime resolution
        proxy_pass $pg_backend;
        proxy_timeout 5m;
        proxy_connect_timeout 30s;
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  # FIX: Target the 'default' (production) namespace
  name: nginx-pg-proxy
  namespace: default
  labels:
    app: nginx-pg-proxy
    purpose: pg-proxy
spec:
  selector:
    matchLabels:
      app: nginx-pg-proxy
      purpose: pg-proxy
  template:
    metadata:
      labels:
        app: nginx-pg-proxy
        purpose: pg-proxy
    spec:
      nodeSelector:
        role: database
      tolerations:
        - operator: Exists
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          args: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
          ports:
            # FIX: Expose the correct SSL port (5433)
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            # FIX: Mount path should match the ssl_certificate path
            - name: tls-dbprod
              mountPath: /etc/nginx/tls/dbprod
              readOnly: true
          securityContext:
            runAsUser: 0
      volumes:
        - name: config
          configMap:
            name: nginx-pg-proxy-config
            items:
              - key: nginx.conf
                path: nginx.conf
        # FIX: Use the correct production TLS secret
        - name: tls-dbprod
          secret:
            secretName: newsapp-db-prod-tls
  updateStrategy:
    type: RollingUpdate