apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-pg-proxy-config
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  nginx.conf: |
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    stream {
      # Use Kubernetes's internal DNS for runtime resolution
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;

      server {
        # Listen on the container's port 5433
        listen 5433 ssl;
        ssl_certificate /etc/nginx/tls/dbprod/tls.crt;
        ssl_certificate_key /etc/nginx/tls/dbprod/tls.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Forward traffic to the production DB service on port 5432
        proxy_pass postgresql-prod.default.svc.cluster.local:5432;
        proxy_timeout 5m;
        proxy_connect_timeout 30s;
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-pg-proxy
  namespace: default
  labels:
    app: nginx-pg-proxy
    purpose: pg-proxy
spec:
  selector:
    matchLabels:
      app: nginx-pg-proxy
      purpose: pg-proxy
  template:
    metadata:
      labels:
        app: nginx-pg-proxy
        purpose: pg-proxy
    spec:
      nodeSelector:
        role: database
      tolerations:
        - operator: Exists
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          args: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
          ports:
            # Expose the production proxy on host port 5433
            - containerPort: 5433
              hostPort: 5433
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: tls-dbprod
              mountPath: /etc/nginx/tls/dbprod
              readOnly: true
          securityContext:
            runAsUser: 0
      volumes:
        - name: config
          configMap:
            name: nginx-pg-proxy-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: tls-dbprod
          secret:
            secretName: newsapp-db-prod-tls
  updateStrategy:
    type: RollingUpdate