# clusters/prod/apps/pgpool-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgpool-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" 
spec:
  project: newsapp-prod
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: pgpool
    targetRevision: 4.5.7
    helm:
      valueFiles:
        - ../../values/pgpool/prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true