apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: newsapp-prod
  namespace: argocd
spec:
  description: "Environment project for newsapp"
  sourceRepos:
    - https://github.com/eli-pavlov/newsapp-manifests.git
    - https://charts.jetstack.io 
    - https://helm.runix.net 
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: policy
      kind: PodDisruptionBudget
  namespaceResourceWhitelist:
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: networking.k8s.io
      kind: Ingress
