---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-secret-access-key
  namespace: default
spec:
  encryptedData:
    AWS_SECRET_ACCESS_KEY: AgAe6BuRbA0Zx8mxoeslDV8Cd0ouLyvPIC6Nt/8qFrPyTcGanl1DLp/82Ise07TTi30ZOcKa58Tqbr0OKRimgoA1CbVf7Q4MUo02/Z+96x3RkA/PHNNF5L5kMCglYuYU2bjyLztHSJI17A8e37vJLfM0rpJWR8dtDqGDRcZGg+AsKy8njLbGUDLBf61SB6mviwcN7Seh8YLTvKmUH0ISxgC6kHKnTk5jahKSEkC5Le3rl+EtBI2RRF6aEiZxNGbcJTVdKMZZ/96htCN2uLXsz2hTsavp6edwU4UlOdK3dvmbQCRbMlBx1xLtZy+bls241fwJL+dnM64j8jVpMsXC7KQXjcBNvrCXD883uTp/CaO+aocjVnbIYKwyNVfDG//ZYIqjznAWGL/kFzQU1jCzaYoCcnnjljAHgQzi40ziCYkIEpoFpOQR4zV1mRqGbqhjw0HWZbgDUQbXN58ANGe/24fBmiEczgFTEyLrz/WLv4IPPcvYY7F9v4MGa0GKvFCb67mXEO//25FeEhr4NqJ5vGlYMlhKQg+NIbt4XlbGCbtprEDmwGqXQXSPzSSwfzfhlEMmrPxa2aejBk6RIIifkBFwQEE72697Z4wDkYjhHymW7udgf60LjuS+BaGSKgsLd0lbPa31Ne3x/jz8vCmO5+OceRnGZPh/OACM4B+3amMXKniIHBr54zUM/HF0aILfXoJ4sko0XTAZrK/yazvuYwby+kVTUEa+acoHVfAn9/ZJwezhF8gUeVhE
  template:
    metadata:
      name: aws-secret-access-key
      namespace: default
    type: Opaque
